name: lamp
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  shared_preferences: ^0.5.6+2


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons:
  flutter_svg: 0.18.0
  smooth_star_rating: ^1.1.1
  flutter_range_slider: ^1.5.0
  expand_widget: ^1.1.0
  country_pickers: ^1.3.0
  flutter_switch: ^0.2.0
  expandable: ^4.1.4






dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true


  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/shadow 1.png
    - assets/images/shadow 2.png
    - assets/images/points.png
    - assets/images/lines.png
    - assets/images/logo.svg
    - assets/images/bg.svg
    - assets/images/indicator.svg
    - assets/images/bg.png
    - assets/images/right_button.png
    - assets/images/right_button.svg
    - assets/icons/button_cancle.svg
    - assets/images/btn_left.svg
    - assets/icons/user_icon.svg
    - assets/icons/arrow.png
    - assets/icons/Filter.png
    - assets/icons/line_6.png
    - assets/icons/home.svg
    - assets/icons/search.svg
    - assets/icons/search.png
    - assets/icons/i_categories.svg
    - assets/icons/icon_shop.svg
    - assets/icons/filter_black.svg
    - assets/icons/favourite.svg
    - assets/images/sub_bunner.svg
    - assets/images/bunner_image.png
    - assets/images/t_shirt.png
    - assets/images/t_shirt2.png
    - assets/images/t_shirt.svg
    - assets/images/Big Image.png
    - assets/images/artwork.svg
    - assets/images/artwork_cart.svg
    - assets/images/cart_white.svg
    - assets/icons/shopping_cart.svg
    - assets/icons/delete_button.svg
    - assets/icons/shape.png
    - assets/icons/icon_cart.png
    - assets/images/face.png
    - assets/images/face2.png
    - assets/images/face3.png
    - assets/images/circle.png
    - assets/icons/cart.svg
    - assets/icons/share_icon.svg
    - assets/icons/plus.svg
    - assets/icons/minus.svg
    - assets/icons/fav.png
    - assets/icons/button_right.svg
    - assets/icons/filter.svg
    - assets/icons/icon_phone.svg
    - assets/icons/button_left.svg
    - assets/icons/icon_map.svg
    - assets/icons/icon_email.svg
    - assets/images/location.svg
    - assets/images/location.png
    - assets/icons/line.svg
    - assets/icons/button_down.png
    - assets/icons/icon 3.png
    - assets/icons/check_box.png
    - assets/icons/check.png
    - assets/icons/background.png
    - assets/icons/left_arrow.png
    - assets/icons/visa.png
    - assets/icons/mastercard.png
    - assets/icons/mada_logo.png
    - assets/icons/eye_hide.png
    - assets/icons/plus_icon.svg
    - assets/icons/offer_notify.svg
    - assets/icons/order_icon.svg
    - assets/icons/arrow_right.svg
    - assets/images/line.png
    - assets/images/tsh1.png
    - assets/images/tsh2.png
    - assets/images/tsh3.png
    - assets/images/success.svg
    - assets/images/contain.png
    - assets/icons/edit_profile.svg
    - assets/icons/location_icon.svg
    - assets/icons/log_out.svg
    - assets/icons/translate.svg
    - assets/icons/setting_icon.svg
    - assets/icons/ic.svg
    - assets/icons/eye.svg
    - assets/icons/fav.svg
    - assets/icons/favourite.svg
    - assets/icons/eye.png
    - assets/icons/line1.svg
    - assets/icons/line2.svg
    - assets/icons/ellipse.svg
    - assets/icons/ic_arrow_right.svg
    - assets/images/price.svg
    - assets/images/progress1.svg
    - assets/images/progress2.svg
    - assets/images/progress3.svg
    - assets/images/progress1_en.svg
    - assets/images/progress2_en.svg
    - assets/images/preparing.png
    - lib/lang/en.json
    - lib/lang/ar.json

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: DINNextLTArabic
      fonts:
        - asset: assets/fonts/DINNextLTArabic-Black.ttf
        - asset: assets/fonts/DINNextLTArabic-Bold.ttf
        - asset: assets/fonts/DINNextLTArabic-Heavy.ttf
        - asset: assets/fonts/DINNextLTArabic-Light.ttf
        - asset: assets/fonts/DINNextLTArabic-Medium.ttf
        - asset: assets/fonts/DINNextLTArabic-Regular.ttf
        - asset: assets/fonts/DINNextLTArabic-UltraLight.ttf
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf


  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
